version: '3'
services:
  design:
    image: structurizr/lite
    restart: no
    ports:
      - "8080:8080"
    volumes:
      - ./.design:/usr/local/structurizr
    profiles:
      - design
